export const AUTH = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
};

export const TOAST = {
  ERROR: 'ERROR',
  NOTIFICATION: 'NOTIFICATION',
};

export const TABS = {
  CREATE_CONVERSATION: 'CREATE_CONVERSATION',
  FRIENDS_LIST: 'FRIENDS_LIST',
  CONVERSATIONS: 'CONVERSATIONS',
  PROFILE: 'PROFILE',
};

export const CONTENT_TYPES = {
  INTRO: 'INTRO',
  PRIVATE_CONVERSATION: 'PRIVATE_CONVERSATION',
  GENERAL_CONVERSATION: 'GENERAL_CONVERSATION',
};

export const CONVERSATION_TYPES = {
  GENERAL: 'GENERAL',
  PRIVATE: 'PRIVATE',
};
